### ISSUE TITLE
Opção fazer transação na mPos sem precisar de confirmação

### ISSUE THREAD

**Issue by guilhermebruzzi** [stone-pagamentos/Android-Uri-demo#2]
O applinking deve por padrão pedir pra mPos para já efetuar a transação com cartão no pinpad sem precisar de nenhuma ação do usuário.
Se a app de origem quiser editar a transação antes de enviar (uma confirmação), pode ser uma opção extra do applinking.
Atualmente o applinking precisa de confirmação e não permite editar nenhum dado da transação original.

**Comment by jgabrielfreitas** [comment]
@guilhermebruzzi liberamos isso no app v2.1.1 no canal _alpha_!

**Comment by guilhermebruzzi** [comment]
@jgabrielfreitas nice! \o/
