### ISSUE TITLE
Feedback de retorno

### ISSUE THREAD

**Issue by guilhermebruzzi** [stone-pagamentos/Android-Uri-demo#4]
Feedback visual muito discreto de que retornou com sucesso (aumentar o tempo do toast ou criar um alerta com botão de confirmação).

E no pinpad fica escrito: "TRANSAC APROVADA" eternamente se a transação foi feita por esse applinking.

Acredito que poderia antes de retornar da mPos, voltar ao padrão de ficar escrito: STONE PAGAMENTOS, que é o texto que fica se vc faz direto via mPos, sem applinking.

**Comment by jgabrielfreitas** [comment]
@guilhermebruzzi, estamos subindo para alpha a **versão 2.1.2** do app com essa correção

**Comment by guilhermebruzzi** [comment]
@jgabrielfreitas Irado! :D
